[package]
name = "tx"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
itertools = "0.13.0"
pest = "2.7.11"
pest_derive = "2.7.11"
thiserror = "1.0.61"
